version: '3.8'

services:
  authsystem:
    build:
      context: ./AuthSystem
      dockerfile: Dockerfile
    ports:
      - "5236:5236"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=FullAuthSystemDb;User=root;CharSet=utf8mb4;
    depends_on:
      - mysql
    networks:
      - backend-network

  dataservice:
    build:
      context: ./DataService
      dockerfile: Dockerfile
    ports:
      - "5162:5162"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=FullAuthSystemDb;User=root;CharSet=utf8mb4;
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: FullAuthSystemDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge 